### ISSUE TITLE
It is possible to use with desktop app?

### ISSUE THREAD

**Issue by tkowalczyk** [mroach/RollbarSharp#14]
I would like to use with desktop application for example created with WPF.
It is possible? Because I can see some ASP.NET MVC dependencies?

Regards,
Tomasz Kowalczyk

**Comment by cdesch** [comment]
@webcoyote Is there a WPF example available?

**Comment by AlbertoMonteiro** [comment]
@cdesch no, but there is nothing special, its the same api

**Comment by webcoyote** [comment]
I've used the component with desktop & mobile applications in Unity3D, and with service applications; it works fine for all of them.

**Comment by cdesch** [comment]
Thanks @AlbertoMonteiro, I appreciate your quick response. I'll try to get it to work in a WPF application again using this library. I know these may be trivial things, but the time saved by someone who is new C# can be a battle when choosing a library. (Something I really love about the Ruby community with Gems -- 1) drop gem in 2) Drop sample code in 3) see that it is working 4) continue on with customization and usage). I created a pull request [10](https://github.com/rollbar/Rollbar.NET/pull/10 ) on the RollBar.Net library for a working WPF example after I got it work. My understanding was that this library was the one that is more officially maintained by Rollbar as they mention it on their site, although that one is owned by them.

If I can get a WPF sample to work, I'll create one for here too.

**Comment by AlbertoMonteiro** [comment]
@cdesch Here follow some example:

### Configuration

The easiest way to get going is to add the `Rollbar.AccessToken` item to your app settings.

```xml
<configuration>
  <appSettings>
    <add key="Rollbar.AccessToken" value="YOUR_TOKEN_HERE"/>
    <add key="Rollbar.Environment" value="production"/>
  </appSettings>
</configuration>
```
### In any part of your Desktop App(WPF, Windows Forms)

```csharp
try
{
    //Some code
}
catch (Exception ex)
    IRollbarClient rollbarClient = new RollbarClient();
    rollbarClient.SendException(ex);
}
```
