### ISSUE TITLE
Binding Redirect Created when installing Nuget

### ISSUE THREAD

**Issue by Crisfole** [mroach/RollbarSharp#27]
I have JSON.NET (v6.0.0.0) already installed, and when I install RollbarSharp it adds a binding redirect...that's slightly worrying (see http://msdn.microsoft.com/en-us/magazine/jj851071.aspx)

If possible, could the Json.Net dependency be tweaked so this doesn't happen?

**Comment by AlbertoMonteiro** [comment]
@Crisfole the #32 should fix this problem, but @webcoyote must release new version of package.
