### ISSUE TITLE
Release of user params?

### ISSUE THREAD

**Issue by guzart** [mroach/RollbarSharp#28]
Any chance you can make a nuget release to get the userParams out?

Thank you for this simple and clean project.

**Comment by jamescrowley** [comment]
For now I have put an unofficial build as of https://github.com/mroach/RollbarSharp/tree/4b48ad949863e57019f9c804d82b5d1cacc4fa99 on Nuget.org here: https://www.nuget.org/packages/RollbarSharp.Unofficial/

**Comment by guzart** [comment]
Thank you @jamescrowley

**Comment by webcoyote** [comment]
Released 0.3.2.0
