### ISSUE TITLE
NuGet package out of date

### ISSUE THREAD

**Issue by jamescrowley** [mroach/RollbarSharp#29]
Any chance for an updated NuGet package that includes the code_version change?

**Comment by jamescrowley** [comment]
Note: for now I have put an unofficial build as of https://github.com/mroach/RollbarSharp/tree/4b48ad949863e57019f9c804d82b5d1cacc4fa99 on Nuget.org here: https://www.nuget.org/packages/RollbarSharp.Unofficial/

**Comment by webcoyote** [comment]
@mroach: can you make me a maintainer of the RollbarSharp project on NuGet so I can push packages? As you're the only maintainer of the project at present you're the only one who can make updates there.

Thanks!

**Comment by mroach** [comment]
Hey guys, sorry I've been out of touch on this one! @webcoyote do you have the same username handle on NuGet? I'll make you an owner of the project there.

**Comment by webcoyote** [comment]
Yes -- same handle (webcoyote). Thanks!

**Comment by mroach** [comment]
Done! You're now an owner of RollbarSharp and NLog.RollbarSharp

**Comment by jamescrowley** [comment]
:+1:

**Comment by jakejgordon** [comment]
Sweet! @webcoyote Can you update nuget? Would really love to get inner exceptions logging! Also, thanks for making this in the first place @mroach :)

**Comment by mroach** [comment]
@jakejgordon No problem, mate! I'm glad that @webcoyote and others have picked up the baton so this doesn't become abandonware. If he's not around to update it in the next few days I'll see about getting my Windows environment back up and running to build, test, and push.

**Comment by webcoyote** [comment]
Done: Version 0.3.2.0
