### ISSUE TITLE
Catch (exeption)

### ISSUE THREAD

**Issue by jhallam3** [mroach/RollbarSharp#40]
Hi with the following code it doesnt post the exception.. 
catch (Exception ex2)
                {
                    var d = new RollbarClient().SendErrorException(ex2);
                }

the variable d comes back with a id and running fine with other functions.

**Comment by mroach** [comment]
`SendErrorException` is an asynchronous function. It returns a `Task` object so you can optionally do something when the reporting is done. In most cases it's a "fire and forget" operation. So, 'd' is a `Task` and not a result.

See: https://github.com/mroach/RollbarSharp/blob/master/src/RollbarSharp/RollbarClient.cs#L90

**Comment by jhallam3** [comment]
thanks thats worked!

Love it!

thanks again!
