### ISSUE TITLE
Sending person details along with error functionality not available

### ISSUE THREAD

**Issue by bryandh** [mroach/RollbarSharp#45]
I wanted to send additional information to Rollbar about the user that encountered the error. At the moment, this functionality is not available in this package.
I did however notice that @travisrussi has implemented this functionality in a fork of this package; https://github.com/travisrussi/RollbarSharp
Could this functionality be implemented in the core package?
Perhaps @travisrussi could submit a pull request of his version.

**Comment by richardversluis** [comment]
You can do:

```c#
rb.SendException(new Exception(), modelAction: a => a.Person.Username = "TheUser");
```

**Comment by richardversluis** [comment]
@bryandh did the above solution work for you?

**Comment by bryandh** [comment]
@richardversluis First of all, sorry for responding so late to this issue. Thank you very much it works like a charm!
