### ISSUE TITLE
PersonModel for non-web usage

### ISSUE THREAD

**Issue by Atrejoe** [mroach/RollbarSharp#47]
I would be cool if it would be possible to specify the `PersonModel` when logging exceptions.

I took a glance at the code, and the `PersonModel` is only populated when `HttpContext.Current` exists and is then populated from `AUTH_USER`,`LOGON_USER` or `REMOTE_USER` server variables respectively.

Another option is to populate the `Person model` from the environment..... You know what, I'll submit a pull request for that!

**Comment by Atrejoe** [comment]
And done, see #48

**Comment by richardversluis** [comment]
:+1:
