### ISSUE TITLE
Filter/Scrub properties from POST request 

### ISSUE THREAD

**Issue by makenova** [mroach/RollbarSharp#50]
Hi,
  How do I go about defining properties to scrub from a POST request?
I'm currently sending errors with 
```C#
(new RollbarClient()).SendException(exception);
```
Thanks for the help.

**Comment by makenova** [comment]
After some trial and error the solution I'm currently using is:
```C#
new RollbarClient().SendException(exception, null, null, n =>
{
  var scrubList = new List<string> { "credit", "password" };

  n.Request.PostParameters = n.Request.PostParameters
              .Where(p => scrubList.All(s => !p.Key.ToLower().Contains(s)))
              .ToDictionary(p => p.Key, p => p.Value);
});
```
If there is a different/better way to do it, please let me know.

**Comment by richardversluis** [comment]
Hi makenova,

```csharp
var rb = new RollbarClient();
rb.Configuration.ScrubParams = new[] { "session", "password" };
rb.SendException(yourEx);
```

This scrubs headers, session, querystring and post parameters.

**Comment by makenova** [comment]
Thank you!

**Comment by makenova** [comment]
@richardversluis I didn't test that before I closed the issue, what I want is to scrub data that contains words in the scrubList. So "CreditCard.Number" should be scrubbed by "credit". I checked the `Scrub` method in `RequestModelBuilder.cs` and it looks like it's checking for whole word matches.

If there is a way to accomplish that beyond what I already have, I would love to know. 
Otherwise, you can leave this issue closed. Thank you.

**Comment by richardversluis** [comment]
@makenova No, you're correct it only scrubs if there is a 1 on 1 match. In that case your code example is the way to go I guess :)
